### ISSUE TITLE
PSR-17 

### ISSUE THREAD

**Issue by agsachdev** [boundstate/yii2-mailgun#16]
Http\Discovery\Exception\NotFoundException
No PSR-17 url factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation
↵
Caused by: Http\Discovery\Exception\DiscoveryFailedException
Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
- Puli Factory is not available
- No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: .
- No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: Phalcon\Http\Message\UriFactory, Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\UriFactory, GuzzleHttp\Psr7\HttpFactory, Http\Factory\Diactoros\UriFactory, Http\Factory\Guzzle\UriFactory, Http\Factory\Slim\UriFactory, Laminas\Diactoros\UriFactory.

**Comment by mikejpeters** [comment]
You must also install the PSR-7 implementation and HTTP client you want to use, as described in the README.
