### ISSUE TITLE
Compose function not working???

### ISSUE THREAD

**Issue by d0dic** [boundstate/yii2-mailgun#3]
Hi there, 

i took your solution few days ago and on the first test i saw it not functioning, it seems that you did not implement/override compose() method in your mailer or it has some kind of malfunction?

**Comment by mikejpeters** [comment]
Compose functionality is handled by Yii's [`BaseMailer`](http://www.yiiframework.com/doc-2.0/yii-mail-basemailer.html).  We override [`BaseMailer#sendMessage()`](http://www.yiiframework.com/doc-2.0/yii-mail-basemailer.html#sendMessage%28%29-detail) as recommended in the docs.

Please let me know the details of what is going wrong and I can try to help.  An example of how you are using it in your code might be helpful.

**Comment by ozada** [comment]
Hi i get error when i set setFrom function `->setFrom([$this->from => $this->fromName])`
Can you check why its occurs?

**Comment by andhikamaheva** [comment]
@zinger1989  please check this issue #4

**Comment by mikejpeters** [comment]
Until `v0.0.3` passing an array to `setFrom` wasn't supported by this library. Please let me know if you still have the issue on latest version.
