### ISSUE TITLE
set From Name ?

### ISSUE THREAD

**Issue by andhikamaheva** [boundstate/yii2-mailgun#4]
How can i send email with From Name (Sender Name) ?

**Comment by andhikamaheva** [comment]
Solved, you just add "Name Of your email email@example.com" in setFrom. Like this : 

`Yii::$app->mailer->compose("Email content")->setFrom('Andhika Maheva <me@andhika.id>')->setTo("destination@example.com")->setSubject("The Email Subject")->send();`

**Comment by xiongmaonihao** [comment]
Where are you from?
I come from China
I want to ask you a question.
How does the mailgun API send the fromname。

**Comment by xiongmaonihao** [comment]
mailgun set fromname？
