### ISSUE TITLE
Send batch emails

### ISSUE THREAD

**Issue by DarkDrim** [boundstate/yii2-mailgun#5]
Hello! As can be sent directly to all users?
If I send as: ...-> setTo ($ followers_list)
all users are in the copy, but should be sent separately to each.

**Comment by DarkDrim** [comment]
I mean about "Batch sending": https://documentation.mailgun.com/user_manual.html#batch-sending

**Comment by mikejpeters** [comment]
Finally added in [v1.3.0](https://github.com/boundstate/yii2-mailgun/tree/v1.3.0#batch-sending)
