### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by mits-techreceptives** [boundstate/yii2-mailgun#7]
I am getting below error : 
GuzzleHttp\Exception\RequestException
cURL error 60: SSL certificate problem: unable to get local issuer certificate
↵
Caused by: GuzzleHttp\Ring\Exception\RingException 

how to fix this ? what parameters i am missing during configuration ?
i set up as shown in doc but still it throws error.
i am on window localhost.

**Comment by mrstroz** [comment]
I found solution 
here http://stackoverflow.com/questions/30240840/laravel-5-socialite-curl-error-77-error-setting-certificate-verify-locations
